.travis.yml

Automatically deploy pypi packages for beka.

---

chewie/chewie.py
chewie/eap_state_machine.py
chewie/utils.py
run.py
test/test_full_state_machine.py

Fix Logging not working when used as library in faucet.

---

test/test_full_state_machine.py

issue discovered here
https://github.com/faucetsdn/chewie/pull/39#issuecomment-424529163

fix discard test flakyness

---

chewie/chewie.py

This reverts commit d7e1ae694c79014d0ba2f7df13505993fd65541f.
This is actually needed to run the docker images which are used during development. It did run fine without in the Faucet integration tests.

Revert "remove unneeded code"

---

chewie/chewie.py
chewie/eap_state_machine.py
chewie/message_parser.py
chewie/radius.py
chewie/radius_attributes.py
chewie/radius_datatypes.py
test/test_message_parser.py
test/test_radius.py

Revert "refractor radius attributes. Add more attributes that have the dataty…"

---

chewie/chewie.py
test/test_chewie.py

Local variable naming for chewie.py

Chewie tidy

---

chewie/eap_state_machine.py
test/test_full_state_machine.py

Remove sleep() from the state machine test and add comments where we aren't testing certain paths

Tweak eap state machine tests

---

.gitignore
test/helpers.py
test/test_chewie.py
test/test_full_state_machine.py

This is a unit test, not an integration test. There is more work to be done as we're replicating a lot of the state machine tests here, but this at least cuts a chunk of time out of the test suite.

Improve chewie tests

---

chewie/chewie.py

Exceptions are really important, and if we do get an unexpected one then
we want it to take down the app. Catching known specific exceptions
(e.g. socket died in a messy way) is reasonable, but for the most part
we want these to bubble up to the top.

Remove exception catch-alls

---

.gitignore
build_docs.sh

Add build_docs.sh for building Sphinx documentation.

Add build_docs functionality

---

chewie/chewie.py
chewie/eap_state_machine.py
chewie/message_parser.py
chewie/radius.py
chewie/radius_lifecycle.py
test/test_chewie.py
test/test_radius.py

Create RadiusLifecycle object and move some logic into it

Extract radius lifecycle

---

chewie/auth_8021x.py
chewie/chewie.py
chewie/eap.py
chewie/ethernet_packet.py
chewie/message_parser.py
chewie/radius.py
chewie/radius_attributes.py
chewie/radius_datatypes.py
chewie/utils.py
test/test_message_parser.py
test/test_radius.py

Custom exception for message parsing errors. the original error is stored in the class.
Also pylinted a couple of things.
closes #88

MessageParserError exception

---

Dockerfile.test
README.md
chewie/eap.py
chewie/eap_state_machine.py
chewie/message_parser.py
docker-compose.yaml
etc/wpasupplicant/wired-peap.conf
test/test_message_parser.py

Add PEAP Message Type
Add Example PEAP Configuration for wpa_supplicant
Add Test for PEAP Message Parsing
Add Dockerfile.test for running tests locally.

 Add PEAP Functionality

---

chewie/chewie.py
chewie/eap_state_machine.py
chewie/radius_lifecycle.py
chewie/utils.py
test/test_chewie_mocks.py
test/test_full_state_machine.py

I was passing around a tuple between the state machine and the output queues. Changed it to a namedtuple.

Namedtuple

---

chewie/chewie.py
chewie/eap_state_machine.py
test/test_chewie.py
test/test_full_state_machine.py

snake case for eap state machine rfc variables & functions

---

chewie/eap_state_machine.py
requirements.txt
setup.py
test/test_chewie.py
test/test_full_state_machine.py

Use pytransitions for eap state machine

---

Dockerfile.test
chewie/eap_state_machine.py
run_tests.sh
test/test_full_state_machine.py

Change State Machine Flow to NO_STATE on port re-enable

Port-Up State to Ignore Previous Requests

---

chewie/radius_lifecycle.py

used to create the NASPort RADIUS attribute

change formatter to support ports numbered up to 65535

---

chewie/radius.py
test/test_radius.py

Previously if one did not exist no check would take place, 
closes #106

Check Message-Authenticator and Response-Authenticator if possible.

---

chewie/radius_attributes.py

helpful for https://github.com/faucetsdn/faucet/issues/2832 and https://github.com/faucetsdn/faucet/issues/2830

add tunnel, filter, nas ip radius attributes

---

.travis.yml
run_tests.sh

* Test on python 3.5/3.6/3.7.
* Upgrade from trusty to xenial.
* Run codeclimate only on python 3.6 stage.

Switch to using travis build stages.

---

.gitignore
.readthedocs.yml
docs/Makefile
docs/conf.py
docs/development.rst
docs/index.rst
docs/intro.rst
docs/requirements.txt

Add Configuration Files for ReadTheDocs
Add ReadMe to Docs 
Docs include Sphinx-built documentation

Push Docs to ReadTheDocs

---

chewie/state_machines/eap_state_machine.py
chewie/state_machines/mab_state_machine.py
docs/architecture.rst
docs/conf.py
docs/index.rst
docs/requirements.txt

Add Functionality for Creating State Machine Graphs
Add to Graphs to Docs

Add Graphs to State Machines

---

.codecov.yml
.travis.yml
README.md
run_tests.sh
test-requirements.txt
travis/runtests.sh

Split UnitTests and Integration Tests into Different Travis Stages
Add CodeCov to Repository
BUGFIX: Pytype uses configuration in setup.cfg

Split Travis Functions into Stages

---

chewie/chewie.py
chewie/state_machines/abstract_state_machine.py
chewie/state_machines/eap_state_machine.py
chewie/state_machines/mab_state_machine.py
docs/conf.py

Add metadata to States in State Machines
Add AbstractStateMachine class
Build State Machine Graphs of Core Transitions only

Clean State Machine Graphs

---

chewie/chewie.py
chewie/state_machines/eap_state_machine.py
chewie/utils.py
test/unit/test_chewie.py

See https://github.com/faucetsdn/faucet/issues/3098

Don't use ID 0 to avoid comparison to None. Use get_random_id() consistently.

---

.github/workflows/tests-unit.yml
debian/control
setup.py

https://github.com/faucetsdn/faucet/issues/3844

Remove python 3.5 support.
